### ISSUE TITLE
Insights should always be scoped to the current repository and directory when viewed on a repository or directory page (overriding the repositories listed at creation)

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph-search-insights#6]
Insights that display themself on the directory page should always show info about the current directory but not the chart with repositories from the insight user or organization settings.

**Comment by Joelkw** [comment]
To clarify/confirm my expectations: if I set up an insight running over sourcegraph/sourcegraph, but then I click into the repo page for sourcegraph/sourcegraph and click into a subdirectory folder, then the insight that runs on that page should show me just the results for that subfolder.
